# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page_metadescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='metaDescription',
        ),
    ]
